In [1]:
import tensorflow as tf

In [2]:
!pip install mitdeeplearning

     |████████████████████████████████| 2.1 MB 2.0 MB/s eta 0:00:01
     |████████████████████████████████| 1.5 MB 2.6 MB/s eta 0:00:01
  Created wheel for mitdeeplearning: filename=mitdeeplearning-0.2.0-py3-none-any.whl size=2115440 sha256=dd5dc4c627dc953725e2b807360e33cebbb0116dd3c1790f374427bfd0b96f1d
  Stored in directory: /Users/Sunny_Charlie/Library/Caches/pip/wheels/2e/45/44/c5b304f31f37e8d2315f9e969fd8cdb0014a5c28608d0bf410
  Created wheel for gym: filename=gym-0.21.0-py3-none-any.whl size=1616824 sha256=3c3ca1ec6b63fb7b20196cfb2925b5a5f7af43637d84209d07dbadfd783184a7
  Stored in directory: /Users/Sunny_Charlie/Library/Caches/pip/wheels/27/6d/b3/a3a6e10704795c9b9000f1ab2dc480dfe7bed42f5972806e73
Successfully built mitdeeplearning gym


In [40]:
# import mitdeeplearning as mdl
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://tensorflownet.readthedocs.io/en/latest/_static/tensor-naming.png")

In [188]:
#from mitdeeplearning import lab1
#import mitdeeplearning as mdl

## 1. TensorFlow Brief

TensorFlow is called 'TensorFlow' because it handles the flow (node/mathematical operation) of Tensors, which are data structures that you can think of as multi-dimensional arrays. Tensors are represented as n-dimensional arrays of base dataypes such as a string or integer -- they provide a way to generalize vectors and matrices to higher dimensions.

The ```rank``` of a Tensor provides the number of dimensions (n-dimensions) -- you can also think of this as the Tensor's order or degree.

The ```shape``` of a Tensor defines its number of dimensions and the size of each dimension. //How many values in side each dimension.

Let's first look at 0-d Tensors, of which a scalar is an example:

### 1.1 Scalar - 0 Dimension, Constant

In [8]:
sport = tf.constant("Tennis", tf.string)

In [17]:
constant_2 = tf.constant(2, dtype=tf.float64)

In [18]:
number = tf.math.sqrt(constant_2)

In [20]:
print("'Sport' is a {}-d Tensor".format(tf.rank(sport).numpy()))

'Sport' is a 0-d Tnsor


In [21]:
print("'number' is a {}-d Tensor".format(tf.rank(number).numpy()))

'number' is a 0-d Tensor


### 1.2 Vector,  List - 1 Dimention Tensors

In [23]:
sports = tf.constant (["Tennis", "Basketball"], tf.string)

In [28]:
numbers = tf.constant ([3.141592, 1.4142213, 2.71821], tf.float64)

In [35]:
print("'Sports' is a {}-d Tensor with shape: {}".format(tf.rank(sports).numpy(), tf.shape(sports)))

'Sports' is a 1-d Tensor with shape: [2]


In [37]:
print("`Numbers` is a {}-d Tensor with shape: {}".format(tf.rank(numbers).numpy(), tf.shape(numbers)))

`Numbers` is a 1-d Tensor with shape: [3]


### 1.3 Metrix - 2-D Dimentions Tensor

In [45]:
matrix = tf.constant([[1.0, 2.0, 3.0, 4.0], [5, 6, 7, 8]], tf.float32)

In [46]:
matrix

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [47]:
assert isinstance(matrix, tf.Tensor)

In [49]:
assert tf.rank(matrix).numpy()==2

### 1.4 Multiple Dimentions Tensor

In [77]:
# tf.zeros(shape, dtype=tf.dtypes.float32, name=None)

#### 1.4.1 Shape provide the number of elements in each Tensor Dimention

In [92]:
a=tf.zeros(shape=4, dtype=tf.dtypes.float32)

#### 1.4.2 4-D Tensor: 10 Images with 256x256 pixel with GRB 3 colors chanel.

In [79]:
images = tf.zeros([10, 256, 256, 3], tf.int32)

In [80]:
assert isinstance(images, tf.Tensor)

In [81]:
assert tf.rank(images).numpy() == 4

In [76]:
images

<tf.Tensor: shape=(10, 256, 256, 3), dtype=int32, numpy=
array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0

In [69]:
import pandas as pd

In [73]:
Image(url= "https://miro.medium.com/max/2000/1*8mlH1a4MEOxr6wDjCZE8Ug.png")

In [82]:
assert tf.shape(images).numpy().tolist() == [10, 256, 256, 3]

In [93]:
print("'images' is a {}-d Tensor with shape: {}".format(tf.rank(images).numpy(), tf.shape(images)))

'images' is a 4-d Tensor with shape: [ 10 256 256   3]


#### 1.4.3 Use Slicing to access subtensors within a hgher-rank Tesor

In [94]:
matrix

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [95]:
row_vector = matrix[1]

In [96]:
row_vector

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([5., 6., 7., 8.], dtype=float32)>

In [97]:
column_vector = matrix[:, 2]

In [98]:
column_vector 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

In [99]:
scalar = matrix[1,2]

In [100]:
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [101]:
print("'row_vector': {}".format(row_vector.numpy()))

'row_vector': [5. 6. 7. 8.]


In [102]:
print("'column_vector': {}".format(column_vector.numpy()))

'column_vector': [3. 7.]


In [103]:
print("'scalar': {}".format(scalar.numpy()))

'scalar': 7.0


## 2. Computation on Tensors

In [104]:
a = tf.constant(15)

In [105]:
b = tf.constant(16)

In [107]:
c1 = tf.add(a,b)

In [108]:
c2 = a + b

In [112]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=31>

In [113]:
c2

<tf.Tensor: shape=(), dtype=int32, numpy=31>

In [114]:
matrix1 = tf.constant([[1,2], [3,4]], tf.int16)

In [144]:
matrix2 = tf.constant([['a','b'], ['c','d']], tf.string)

In [145]:
matrix1

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 2],
       [3, 4]], dtype=int16)>

In [146]:
matrix2

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [150]:
def func(a,b):
    c = tf.add(a,b)
    d = tf.subtract(b,1)
    e = tf.multiply(c, d)
    return e

In [152]:
func(4,5)

<tf.Tensor: shape=(), dtype=int32, numpy=36>

## 3. Neural Networks in TensorFlow

In [206]:
class DenseLayer(tf.keras.layers.Layer): 
    def __init__(self, num_output_nodes):    #Constructor
        super(DenseLayer, self).__init__()
        self.num_output_nodes = num_output_nodes

In [207]:
    def build(self, input_shape):  # Build Weight and bias
        d = int (input_shape[-1])
        self.w = self.add_weight ("weight", shape=[d, self.num_output_nodes])
        self.b = self.add_weight ("bias", shape=[1, self.num_output_nodes])

In [208]:
    def call (self, x):    # Compute output y
        z = tf.matmul(x, self.W) + self.b
        y = tf.sigmoid(z)
        return y

In [213]:
tf.random.set_seed(1)
myLayer = DenseLayer(3)
myLayer.build((1,2))   # 1-> W, 2->bias
x_input = tf.constant([6,4], tf.int16, shape=(1,2))  # x_input is as a shape of 1-row, 2-col, with values are [3, 4]
y = myLayer.call(x_input) 


In [214]:
x_input

<tf.Tensor: shape=(1, 2), dtype=int16, numpy=array([[6, 4]], dtype=int16)>

In [215]:
print(y.numpy())

[[6 4]]


In [212]:
mdl.lab1.test_custom_dense_layer_output(y)

NameError: name 'mdl' is not defined